### ISSUE TITLE
Request: Display as a countdown, autonomous analog system

### ISSUE THREAD

**Issue by NdrsAM** [harry75369/ESP8266_Tomato#1]
It could be a new feature.
Adding a segment display, using the TM1637 library or similar, could be useful for displaying the countdown of both periods, working and rest. 

It would make the system more autonomous to the UI interface.

**Comment by harry75369** [comment]
sounds interesting, however, I don't have any display hardware, the only display is provided through web ui. It just works so I don't expect more changes. You can fork it if you want to implement this on your own.
